include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  
linter:
  rules:
    # Deshabilitar reglas que generan muchos warnings en desarrollo
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_null_comparison: false
    unnecessary_non_null_assertion: false
    unused_local_variable: false
    unused_field: false
    unused_import: false
    library_prefixes: false
    unnecessary_nullable_for_final_variable_declarations: false
    deprecated_member_use: false
    use_key_in_widget_constructors: false
    library_private_types_in_public_api: false
    prefer_final_fields: false
    use_super_parameters: false
    sized_box_for_whitespace: false
    unnecessary_brace_in_string_interps: false
    sort_child_properties_last: false
    prefer_interpolation_to_compose_strings: false