name: cubalink23
description: "CubaLink23 - Tu conexión con Cuba para recargas y servicios."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  http: ^1.2.0
  app_links: ^6.1.4
  flutter_local_notifications: ^17.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  share_plus: ^7.2.2
  google_sign_in: ^6.2.1
  square_in_app_payments: ^1.7.11
  # contacts_service: ^0.6.3  # Temporalmente deshabilitado para compilación
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo_app.png
    - assets/images/wallet_icon.png
    # New category icons (final versions)
    - assets/Untitled design 2/Alimentos.png
    - assets/Untitled design 2/Deportes.png
    - assets/Untitled design 2/Electronicos.png
    - assets/Untitled design 2/Farmacia.png
    - assets/Untitled design 2/Ferreteria.png
    - assets/Untitled design 2/Hogar.png
    - assets/Untitled design 2/Materiales.png
    - assets/Untitled design 2/Restaurantes.png
    - assets/Untitled design 2/Ropa.png
    - assets/Untitled design 2/Servicios.png
    - assets/Untitled design 2/SUPERMERCADO.png
    # Explicit image declarations to ensure inclusion on Android (filenames with spaces/case)
    - assets/images/Actividad.png
    - assets/images/agregar balance.png
    - assets/images/Amazon.png
    - assets/images/Mensajeria.png
    - assets/images/Recarga.png
    - assets/images/Refiere y gana.png
    - assets/images/Tienda.png
    - assets/images/Transfiere Saldo.png
    - assets/images/Viajes.png
    - assets/images/alimentos.png
    - assets/images/materiales.png
    - assets/images/ferreteria.png
    - assets/images/farmacia.png
    - assets/images/electronicos.png
    - assets/images/ropa.png
    - assets/images/restaurantes.png
    - assets/images/deportes.png
    - assets/images/hogar.png
    - assets/images/servicios.png
    - assets/images/SUPERMERCADO.png
    - assets/documents/
    - assets/text/
    - assets/other/
