name: cubalink23
description: "CubaLink23 - Tu conexión con Cuba para recargas y servicios."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  share_plus: ^7.2.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo_app.png
    - assets/images/wallet_icon.png
    - assets/documents/
    - assets/text/
    - assets/other/
