#!/bin/bash

echo "🔥 MODO DESARROLLO RÁPIDO - CubaLink23"
echo "======================================"
echo ""
echo "📱 App ejecutándose en: http://localhost:8080"
echo "🔄 Hot Reload: ACTIVADO (guardar archivo = ver cambios)"
echo ""
echo "✅ CAMBIOS INSTANTÁNEOS (solo guardar archivo):"
echo "   • Colores, textos, tamaños"
echo "   • Layouts y posiciones"
echo "   • Iconos e imágenes"
echo "   • Estilos y decoraciones"
echo ""
echo "⚠️ CAMBIOS QUE REQUIEREN RECOMPILACIÓN:"
echo "   • Nuevas dependencias (pubspec.yaml)"
echo "   • Nuevos imports"
echo "   • Cambios en main.dart"
echo ""
echo "🎯 TU FLUJO DE TRABAJO:"
echo "   1. Edita el código"
echo "   2. Guarda (Ctrl+S)"
echo "   3. Ve cambios INMEDIATAMENTE"
echo "   4. Repite hasta que te guste"
echo ""
echo "🚀 Comandos útiles en la terminal de Flutter:"
echo "   • 'r' = Hot Reload (cambios instantáneos)"
echo "   • 'R' = Hot Restart (reinicio completo)"
echo "   • 'q' = Salir"
echo ""
echo "💡 TIP: Mantén esta terminal abierta y la app ejecutándose"
echo "   para ver cambios instantáneos al guardar archivos."
echo ""
echo "🎨 ¡Empieza a hacer cambios y ve la magia del Hot Reload!"
