name: Android APK (build-test)
on:
  push:
    branches: ["build-test"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Pub Get
        run: flutter pub get

      - name: Build APK (Release)
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: flutter build apk --release -v

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
